-- Production Row Level Security (RLS) Policies
-- Run this SQL in Supabase SQL Editor AFTER testing in staging
-- IMPORTANT: Test all policies thoroughly before enabling in production

-- ============================================
-- 1. PROFILES TABLE
-- ============================================

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Users can read their own profile
CREATE POLICY "users_read_own_profile" ON profiles
  FOR SELECT
  USING (auth.uid() = id);

-- Users can update their own profile (except role)
CREATE POLICY "users_update_own_profile" ON profiles
  FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id AND
    role = (SELECT role FROM profiles WHERE id = auth.uid())
  );

-- Admins can read all profiles
CREATE POLICY "admins_read_all_profiles" ON profiles
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- Admins can update any profile
CREATE POLICY "admins_update_all_profiles" ON profiles
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- ============================================
-- 2. SPORTS TABLE
-- ============================================

-- Enable RLS
ALTER TABLE sports ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can view sports)
CREATE POLICY "public_select_sports" ON sports
  FOR SELECT
  USING (true);

-- Only admins can insert/update/delete sports
CREATE POLICY "admins_manage_sports" ON sports
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- ============================================
-- 3. COURTS TABLE
-- ============================================

-- Enable RLS
ALTER TABLE courts ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can view courts)
CREATE POLICY "public_select_courts" ON courts
  FOR SELECT
  USING (true);

-- Only admins can insert/update/delete courts
CREATE POLICY "admins_manage_courts" ON courts
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- ============================================
-- 4. BOOKINGS TABLE
-- ============================================

-- Enable RLS
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Authenticated users can insert bookings
-- Note: Adjust this if you add user_id column to bookings
CREATE POLICY "authenticated_insert_bookings" ON bookings
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Users can read their own bookings (if user_id column exists)
-- If using user_name, this policy needs adjustment
-- CREATE POLICY "users_read_own_bookings" ON bookings
--   FOR SELECT
--   USING (user_id = auth.uid());

-- For now, allow authenticated users to read bookings
-- (Adjust based on your schema - if bookings have user_id, use policy above)
CREATE POLICY "authenticated_read_bookings" ON bookings
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Admins can read all bookings
CREATE POLICY "admins_read_all_bookings" ON bookings
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- Admins can update/delete any booking
CREATE POLICY "admins_manage_bookings" ON bookings
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- ============================================
-- 5. AUDIT LOGS TABLE (if created)
-- ============================================

-- If you create an audit_logs table:
-- CREATE TABLE IF NOT EXISTS audit_logs (
--   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   user_id uuid REFERENCES auth.users(id),
--   action text NOT NULL,
--   resource text NOT NULL,
--   resource_id text,
--   details jsonb,
--   created_at timestamptz DEFAULT now()
-- );

-- ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Only admins can read audit logs
-- CREATE POLICY "admins_read_audit_logs" ON audit_logs
--   FOR SELECT
--   USING (
--     EXISTS (
--       SELECT 1 FROM profiles p
--       WHERE p.id = auth.uid() AND p.role = 'admin'
--     )
--   );

-- ============================================
-- NOTES
-- ============================================

-- 1. Service role key bypasses RLS - use only server-side after role verification
-- 2. Test all policies in staging before production
-- 3. Monitor Supabase logs for policy violations
-- 4. Adjust policies based on your specific schema (e.g., if bookings have user_id)
-- 5. Consider adding indexes for performance:
--    CREATE INDEX idx_profiles_role ON profiles(role);
--    CREATE INDEX idx_bookings_user_id ON bookings(user_id); -- if column exists

